spring:
  datasource:
    url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

origin.error:
  prefix: SVC
  service-code: 1

  common:
    prefix: GNR
    service-code: 0
    mappings:
      "[java.lang.Exception]":
        message: Uncaught runtime exception
        status: CONFLICT
        error-desc: GENERAL_FAULT_MSG
        error-code: 999
      "[jakarta.validation.ConstraintViolationException]":
        message: Invalid request parameter
        status: CONFLICT
        error-desc: INVALID_REQUEST_ARG
        error-code: 900
      "[org.springframework.web.HttpRequestMethodNotSupportedException]":
        message: Invalid HTTP method used
        status: CONFLICT
        error-desc: METHOD_NOT_ALLOWED
        error-code: 998